### ISSUE TITLE
Separate DSK from bcalm to optimize -abundance [feature request]

### ISSUE THREAD

**Issue by sjackman** [GATB/bcalm#12]
I'd like to optimize the `-abundance` parameter, and to that end it would be nice to separate the `dsk` stage from the `bcalm` stage so that the `-abundance` parameter can be optimized without having to rerun the _k_-mer counting stage.

**Comment by rchikhi** [comment]
i think it's already the case.. if you re-run bcalm giving the .h5 as input, and specify a higher abundance threshold than the one the .h5 was created with, it should properly filter out lower-abundance kmers.

https://github.com/GATB/bcalm/blob/master/src/bcalm_1.cpp#L383

**Comment by sjackman** [comment]
Great. Thanks! I don't have time to test this out right now, but I will do.

**Comment by rchikhi** [comment]
no prob!
