### ISSUE TITLE
Installing bcalm2 on OS X El Capitan

### ISSUE THREAD

**Issue by mayankpahadia1993** [GATB/bcalm#14]
I am trying to install bcalm2 on my Macbook. I am facing issues while compiling the code. More specifically while running the make command. I am using gcc 5.4. These are the steps that I took to build bcalm2 - 
1) Cloning the repo
2) mkdir build
3) cd build
4) cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc-5 -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-5 ..
5) make -j 8 

I have attached the error that pops up during the make command and then stops the script. 
I tried to pass the compiler version during the make command as well (make -j 8 CC=/usr/local/bin/gcc-5 CXX=/usr/local/bin/g++-5) but it gave the same error.

Can you guide me if I am doing something wrong or missing something? Also if you need any other information, let me know.

<img width="1274" alt="screen shot 2016-08-29 at 5 23 48 pm" src="https://cloud.githubusercontent.com/assets/10993191/18068024/6c0bb9de-6e0d-11e6-8cf2-344d297849cb.png">

**Comment by rchikhi** [comment]
Can you please paste the full error message, e.g. on pastebin.com?

**Comment by mayankpahadia1993** [comment]
Attached is the output and errors from the make command
[makeOutput.txt](https://github.com/GATB/bcalm/files/445435/makeOutput.txt)

**Comment by rchikhi** [comment]
hi, I'm sorry, I do not know how to solve this issue.
Bcalm has been tested with gcc 4.8 and clang 3.7, it compiles okay with those..
see https://travis-ci.org/GATB/bcalm
Could you try maybe using one of these compilers?

**Comment by mayankpahadia1993** [comment]
Thanks for the help, I tried again after the recent commit, and it worked with Apple Clang (Apple LLVM version 7.3.0 (clang-703.0.31)). Not sure if I was making some mistake last time, but I tried with clang, gcc-4.8 and gcc-5.4.

**Comment by rchikhi** [comment]
Perfect! It probably wasn't your mistake, I made a few clang compatibility fixes during the last 2 days
