### ISSUE TITLE
MultipleFile problem

### ISSUE THREAD

**Issue by Malfoy** [GATB/bcalm#16]
When we use bcalm on multiple read files like this:

../bcalm/build/bcalm -in file1,file2

we get 
...
Nb bglue threads: 8
unitigs graph destructor called
EXCEPTION: Unable to open bank 'file2.unitigs.fa.glue'

But the files file1,file2.unitigs.fa.glue etc .. exist

**Comment by rchikhi** [comment]
indeed. for now, use the list method. `ls -1 file1 file2 > list_input` then run bcalm with `-in list_input`

**Comment by rchikhi** [comment]
anyway i'd rather not support this "file1,file2,file3" input format.
