### ISSUE TITLE
Very large k problem

### ISSUE THREAD

**Issue by Malfoy** [GATB/bcalm#17]
When using very large k value like 1000 or 10,000.
A segfault occur during the DSK pass
...
[DSK: Pass 1/1, Step 1: partitioning     ]  49.5 %   elapsed:   3 min 53 sec   remaining:   3 min 57 sec   cpu: 100.7 %   mem: [DSK: Pass 1/1, Step 1: partitioning     ]  49.5 %   elapsed:   3 min 53 sec   remaining:   3 min 57 sec   cpu: 100.7 %   mem: [DSK: Pass 1/1, Step 1: partitioning     ]  49.5 %   elapsed:   3 min 53 sec   remaining:   3 min 57 sec   cpu: 100.7 %   mem: [DSK: Pass 1/1, Step 2: counting kmers   ]  49.5 %   elapsed:   3 min 57 sec   remaining:   4 min 2  sec   cpu: 100.7 %   mem: [58640, 66692, 66726] MB zsh: segmentation fault  bcalm -in contigs1.fa -kmer-size 1000 -abundance-min 1

**Comment by rchikhi** [comment]
DSK problem, huh? paging @grizk

**Comment by rchikhi** [comment]
DSK problem, huh? paging @rizkg

**Comment by Malfoy** [comment]
I can precise that the bug start from k=256 ...

**Comment by dbrowneup** [comment]
Today I ran BCALM with `-kmer-size 1000` and it worked for me. Perhaps you should try recompiling? Here's the build I ran today to make it work:
```
#BSUB -J BCALM_k1024 -L /bin/bash -W 2:00
#BSUB -n 10 -R "span[ptile=10] rusage[mem=2700] select[nxt]" -M 2700
#BSUB -o OUT_BCALM_k1024
##
ml EasyBuild/2.9.0
ml EasyBuild-ada/0
ml GCCcore/4.9.3
ml binutils/2.25-GCCcore-4.9.3
ml GCC/4.9.3-2.25
ml numactl/2.0.11-GCC-4.9.3-2.25
ml hwloc/1.11.2-GCC-4.9.3-2.25
ml OpenMPI/1.10.2-GCC-4.9.3-2.25
ml OpenBLAS/0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0
ml gompi/2016a
ml FFTW/3.3.4-gompi-2016a
ml ScaLAPACK/2.0.2-gompi-2016a-OpenBLAS-0.2.15-LAPACK-3.6.0
ml foss/2016a
ml CppUnit/1.12.1-foss-2016a
ml HDF5/1.8.16-foss-2016a
ml Szip/2.1-foss-2016a
ml zlib/1.2.8-foss-2016a
ml ncurses/6.0-foss-2016a
ml CMake/3.5.2-foss-2016a
ml Doxygen/1.8.11-foss-2016a
#
cd /scratch/user/dbrowne/Software/bcalm/build
#
cmake -DCMAKE_INSTALL_PREFIX=/scratch/user/dbrowne/Software/bcalm/build \
-DCMAKE_C_COMPILER='gcc' -DCMAKE_Fortran_FLAGS='-O2 -march=native' \
-DCMAKE_CXX_FLAGS='-O2 -march=native' -DCMAKE_CXX_COMPILER='g++' \
-DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_C_FLAGS='-O2 -march=native' \
-DCMAKE_VERBOSE_MAKEFILE=ON -DKSIZE_LIST="32 64 128 256 512 1024" .. && make -j 10
```

Our system runs CentOS 6 and uses LSF for batch processing (https://sc.tamu.edu/wiki/index.php/Ada). I can provide a more complete build log, if that would help!

**Comment by rizkg** [comment]
Hi, thanks for your help. There was indeed a bug, but it did not occur for every dataset.
I updated gatb-core to fix the issue, it should be pushed into bcalm soon.

**Comment by rchikhi** [comment]
thanks for the investigation and fixes, guys. The master branch of bcalm now has the fix.
