### ISSUE TITLE
Suggestion: implement -abundance-max [int]

### ISSUE THREAD

**Issue by dbrowneup** [GATB/bcalm#18]
Hi guys,

As the title suggests, I think a really nice feature would be an `-abundance-max` parameter that would easily allow us to exclude kmers with counts above this threshold.

Right now in order to do this I have to run Jellyfish count and then dump specifying `-U [int]` and then running BCALM with the same kmer size on the dumped fasta. It works but it's a pain in the ass and would be nice if BCALM could directly filter out high-abundance kmers.

Cheers!

**Comment by rchikhi** [comment]
Hi Dan,
The good folks at https://github.com/GATB/gatb-core had already implemented that abundance-max feature, but I didn't expose it in Bcalm because i thought it wouldn't be useful. Well, I just turned it back on for you :) just checkout this master branch and you'll be good to go.

**Comment by dbrowneup** [comment]
Fantastic, thank you Rayan! Recompiling now.

**Comment by rchikhi** [comment]
you're welcome! curious what you're using this max abundance threshold for.
