### ISSUE TITLE
When running with multiple threads bcalm reports some wrong links in the FASTA headers

### ISSUE THREAD

**Issue by mpre** [GATB/bcalm#21]
Hi,
as stated in the object of this issue, bcalm outputs some wrong links in the FASTA headers when running with multiple threads.
For example, when running with 4 threads bcalm outputs the following 3 unitigs (this is a subset of the whole FASTA file):

```
>17218 LN:i:39 KC:i:855 KM:f:95.0 L:-:2543:+ L:-:28347:+ L:+:23183:- L:+:31763:- 
AGGAGCGAGCGATTGTAACTTGGTGTTATCCAGACTGGC
>2543 LN:i:31 KC:i:5 KM:f:5.0 L:+:37145:+ 
AGGCATACTTCCAAATGCCCCCGTCTCGAAG
>2544 LN:i:33 KC:i:281 KM:f:93.7 L:-:17218:+ L:+:2542:- L:+:29893:+ 
GATAACACCAAGTTACAATCGCTCGCTCCTCTA
```

As you can see, unitig 17218 reports an incorrect link with unitig 2543 with orientation -+  and the dual link is not in the header of unitig 2543.

The link should be 17218(-) -> 2544(+) and you can find it in the header of unitig 2544.

If I run the tool with only one thread, the unitigs change IDs and the links are correct (the ID mapping are 17218 -> 17435, 2543 -> 13814, 2544 -> 1213)

```
>17435 LN:i:39 KC:i:855 KM:f:95.0 L:-:1213:+ L:-:28181:+ L:+:19629:- L:+:28584:+ 
AGGAGCGAGCGATTGTAACTTGGTGTTATCCAGACTGGC
>13814 LN:i:31 KC:i:5 KM:f:5.0 L:+:37228:- 
AGGCATACTTCCAAATGCCCCCGTCTCGAAG
>1213 LN:i:33 KC:i:281 KM:f:93.7 L:-:17435:+ L:+:1212:- L:+:29855:+ 
GATAACACCAAGTTACAATCGCTCGCTCCTCTA
```

In this case both links are correctly reported as 17345(-) -> 1213(+) and 1213(-) -> 17345(+).

I found this behavior only when running with multiple threads but I'm not sure this never happens with a single thread.

I obtained the previous results with `-kmer-size 31 -min-abundance 5` , I can share the input and output files if you want to take a look at them or reproduce this behavior.

**Comment by rchikhi** [comment]
hi Marco!
Thanks for the very detailed bug report. Am in the process of recoding some aspects of bcalm, so will see if I can run into this issue. If you have any small input where you can reproduce the problem, yes please do share it with me (email is fine).

**Comment by rchikhi** [comment]
Several months after.. I finally found and fixed that nasty multithreading bug (for the story: took me several days of inefficient investigation with breaks due to frustration).
Thanks much for taking the time to provide the small test datasets! these were invaluable.
