### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by nithvarma** [GATB/bcalm#22]
Hi,

I am trying to compile bcalm on my Surface Pro. I am using cygwin64 and gcc 5.4. I got a bunch of warnings while running cmake and running the Make command resulted in errors. All the errors were about some functions (stderror_r(..) and fseeko(..)) not being declared in scope.  I am also attaching the outputs of cmake and make. Could you please help me out?

Thanks in advance,
Nithin

[output-of-cmake.txt](https://github.com/GATB/bcalm/files/1017487/output-of-cmake.txt)
[output-of-make.txt](https://github.com/GATB/bcalm/files/1017488/output-of-make.txt)

**Comment by rchikhi** [comment]
hi Nithin,
I tried to fix these issues for cygwin. I'm surprised there aren't more, noone tests our gatb-core module with cygwin..
to update your bcalm version:

    cd gatb-core && git pull && cd .. && cd build && make -j 8

**Comment by nithvarma** [comment]
Hi Rayan,

Thanks a lot for the quick reply. I shall update it and let you know if there are still problems.

Thanks,
Nithin

**Comment by nithvarma** [comment]
I am still getting similar errors. I think I will try installing it on my Mac. Thanks again :)

**Comment by rchikhi** [comment]
oh, really? i'd be curious to see the new make log, but otherwise, okay

**Comment by nithvarma** [comment]
Sorry for the delayed reply, Rayan. Attaching the error files. 
[output-of-cmake.txt](https://github.com/GATB/bcalm/files/1029597/output-of-cmake.txt)
[output-of-make.txt](https://github.com/GATB/bcalm/files/1029596/output-of-make.txt)

**Comment by rchikhi** [comment]
Thanks. It looks like you were still using the old gatb-core submodule version. For instance you see, at the first error in Exception.hpp, line 140 doesn't correspond to the same line as indicate in the make output anymore (https://github.com/GATB/gatb-core/blob/master/gatb-core/src/gatb/system/api/Exception.hpp#L140).

I've updated bcalm repository, can you try doing a 'git pull' again? It is low priority by the way.

**Comment by nithvarma** [comment]
Thank you so much Rayan, for helping me out. I had done a git pull after you had made the changes. I am not sure why it still did not get updated. 

When I did a `git status' command in the folder /bcalm/gatb-core, it displayed a detached HEAD message with HEAD detached at 2aa4891e. 

I later created a new folder /temp/ and did another clone of the repository in that folder. I got the detached HEAD message again, when I did a `git status' inside /temp/bcalm/gatb-core. This time, though the message was `HEAD detached 0d8a9203', which I think corresponds to a commit on May 24, 2017. Trying to compile, again gave me error messages. But, this was not the latest commit, right? I am attaching the error log. 
[output-of-make.txt](https://github.com/GATB/bcalm/files/1034531/output-of-make.txt)

**Comment by rchikhi** [comment]
hi Nithin, thanks for the details. `git pull` does not automatically update the submodules, that would explain it. I misunderstood your latest answer, and now I realize that the problem isn't resolved, right? A possibility is to update gatb-core manually, i.e. go into the gatb-core folder and do a `git pull origin master` inside it`. This will force to get the very latest version.

**Comment by nithvarma** [comment]
Thanks for the answer on how to update gatb-core. I started using bcalm on my MAC afterwards and things have been running smoothly. 

However, I shall try compiling it again on Cygwin after updating gatb-core the way you suggested.

**Comment by rchikhi** [comment]
Hi Nithin, should I keep this issue open?

**Comment by nithvarma** [comment]
Hi Rayan, I shall close it. Sorry for keeping it open for this long. I am no longer trying to use BCALM on Cygwin.

**Comment by rchikhi** [comment]
ok!
