### ISSUE TITLE
execution error for kmer-size different from 17

### ISSUE THREAD

**Issue by vbonnici** [GATB/bcalm#23]
Hi,
I tried to run the example run-tiny.sh and it rises a segmentation fault.
I tried with a bigger input fasta file but with no better result.
It works only if I use -kmer-size 17, and no other size is working.

Thank you.

**Comment by rchikhi** [comment]
At first i thought "no way that run-tiny segfaults" and then I tested, and you were right 😱, it crashes on my machine too. Actually this is linked to a recent bug for kmers that are multiple of 4. Did you try k=13,14,15 in your investigation?
I'll temporarily disable k-mers multiple of 4 in bcalm until the bug (in DSK) is resolved.

**Comment by vbonnici** [comment]
unfortunately it runs only for k equal to 17 and 31 :(

**Comment by rchikhi** [comment]
hi! There has been some bugfixes and I retested today, all the k values seem to work (except multiples of 4).

**Comment by vbonnici** [comment]
Dead Rayan
Thank you for your work and response.
I will plan to run again the code of my is student.

Bests,
Vincenzo

On Dec 17, 2017 11:57 PM, "Rayan Chikhi" <notifications@github.com> wrote:

hi! There has been some bugfixes and I retested today, all the k values
seem to work (except multiples of 4).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GATB/bcalm/issues/23#issuecomment-352292844>, or mute
the thread
