### ISSUE TITLE
BCALM exception: This dataset has no solid k-mers

### ISSUE THREAD

**Issue by nithvarma** [GATB/bcalm#24]
[output copy.txt](https://github.com/GATB/bcalm/files/1083227/output.copy.txt)
I get the above exception when running BCALM on the set of all 50-mers of the ecoli genome (given in FASTQ format).

**Comment by pashadag** [comment]
What is the command line? Also check the min-abundance parameter, it is probably throwing out all singleton kmers.

**Comment by nithvarma** [comment]
The command line was ./bcalm -in /PATH/reference-reads.fq -kmer-size 50 -abundance-min 1

With an abundance-min parameter of 1 it should not filter out any of the k-mers, I think.

**Comment by rchikhi** [comment]
Hi Nithin,
Something might be wrong with the input file. Can you please paste the first few lines?

**Comment by nithvarma** [comment]
Hi Rayan,

Here are the first few lines of the .fq file that I am using as input to bcalm.

@U00096.2_1_50_0:0:0_0:0:0x1/1
agcttttcattctgactgcaacgggcaatatgtctctgtgtggattaaa
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_2_51_0:0:0_0:0:0x2/1
gcttttcattctgactgcaacgggcaatatgtctctgtgtggattaaaa
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_3_52_0:0:0_0:0:0x3/1
cttttcattctgactgcaacgggcaatatgtctctgtgtggattaaaaa
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_4_53_0:0:0_0:0:0x4/1
ttttcattctgactgcaacgggcaatatgtctctgtgtggattaaaaaa
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_5_54_0:0:0_0:0:0x5/1
tttcattctgactgcaacgggcaatatgtctctgtgtggattaaaaaaa
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_6_55_0:0:0_0:0:0x6/1
ttcattctgactgcaacgggcaatatgtctctgtgtggattaaaaaaag
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_7_56_0:0:0_0:0:0x7/1
tcattctgactgcaacgggcaatatgtctctgtgtggattaaaaaaaga
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_8_57_0:0:0_0:0:0x8/1
cattctgactgcaacgggcaatatgtctctgtgtggattaaaaaaagag
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_9_58_0:0:0_0:0:0x9/1
attctgactgcaacgggcaatatgtctctgtgtggattaaaaaaagagt
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_10_59_0:0:0_0:0:0xa/1
ttctgactgcaacgggcaatatgtctctgtgtggattaaaaaaagagtg
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@U00096.2_11_60_0:0:0_0:0:0xb/1
tctgactgcaacgggcaatatgtctctgtgtggattaaaaaaagagtgt
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII

**Comment by rchikhi** [comment]
Thanks. Those sequences are of length 49, I believe this command line will work:
     ./bcalm -in /PATH/reference-reads.fq -kmer-size 49 -abundance-min 1

**Comment by nithvarma** [comment]
My bad. I missed the fact that the last character in a string of length 50 is the end-of-line character. Thanks a lot Rayan, for spotting the issue. It worked with the value 49.
