### ISSUE TITLE
Different output file sizes

### ISSUE THREAD

**Issue by Ritu-Kundu** [GATB/bcalm#29]
I am running the tool with two pair-end fastq.gz files (High Coverage Human Genome from the 1000Genome project -- SRR1291070_1 (26G) and SRR1291070_2 (24G)).
Every run is producing a resulting unitig file with different size.

The output-log ends with a series of "Couldn't flush" (log file attached).

The available disk space after .h5 file (64G) is produced is about 42G. Is it sufficient or could low disk space be the root of this problem?
[bcalm_result.txt](https://github.com/GATB/bcalm/files/1719685/bcalm_result.txt)

**Comment by rchikhi** [comment]
Dear Ritu,

Most likely this is a disk space problem. Please retry on a drive where you have at least 100-200 GB free.

Best,
Rayan

**Comment by Ritu-Kundu** [comment]
Thanks, Rayan. I will try with more disk space and get back.

Best wishes,
Ritu

**Comment by Ritu-Kundu** [comment]
Thanks, Rayan. Running the tool with increased disk space solved the issue.
Your tool as well as prompt support is much appreciated.
