### ISSUE TITLE
Bug when using BCalm for large k values

### ISSUE THREAD

**Issue by leoisl** [GATB/bcalm#3]
Hello,

I tried to use BCalm on this [small_example.zip](https://github.com/GATB/bcalm/files/141100/small_example.zip) with k=41 and it did not work (for k=31, it works perfectly though). The BCalm step, itself, worked correctly and it was invoked as ./bcalm -in rf -k 41 -abundance 2 . The BGlue step, however, gave an error message and it was invoked as ./bglue -in unitigs.h5 -k 41:
```
Gluing partition 127 (size: 0 MB)               18:50:33     memory [current, maxRSS]: [   7,    0] MB
bglue(78546,0x700000081000) malloc: *** mach_vm_map(size=6072894397144846336) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Gluing partition 128 (size: 0 MB)               18:50:33     memory [current, maxRSS]: [   7,    0] MB
```
Several other similar malloc errors succeeded this one. Weirdly enough, for k=31, it works perfectly. Am I doing something wrong or is this indeed a bug?

**Comment by rchikhi** [comment]
thanks for reporting this bug.

I can reproduce the problem. bcalm seems broken with k>32 right now. We'll fix this asap and let you know.

**Comment by rchikhi** [comment]
appears resolved in latest build
but let's wait until https://github.com/GATB/bcalm/issues/2 is resolved for confirmation

**Comment by Malfoy** [comment]
Seem to work when compiled for k>31
#define kmer __uint128_t 
should be uncommented at the beginning of binSeq.h (line 24)
This is now the default behavior.

**Comment by rchikhi** [comment]
Seems resolved. Leandro?

**Comment by leoisl** [comment]
Yes, it works great now! Thanks! Sorry for the delay.
