### ISSUE TITLE
k-mer count > reference

### ISSUE THREAD

**Issue by simonepignotti** [GATB/bcalm#33]
Hi,

I am puzzled by the result of BCALM in one of my experiments.
With the main purpose of removing duplicate k-mers from the human genome reference, I ran the following command:
```
bcalm -in GRCh38_latest_genomic.fna -kmer-size 31 -nb-cores 20 -abundance-min 1 -max-memory 30000
```
Apart from another know issue (#15) which highly affected the results (557 contigs and 3.1GB for the reference VS 39253840 unitigs and 6.7GB with k=31, 56968323 unitigs and 8.4GB with k=25), I noticed that the k-mer count of BCALM's output is slightly greater than the one of the reference.
To be precise, the 31-mer count of GRCh38_latest_genomic.fna is 2504380308 while BCALM's is 2504381531 (1223 more), and the 25-mer count is respectively 2386251821 and 2386252760 (939 more).

Here is the link to the reference version I used:
ftp://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz
The k-mer count was obtained using jellyfish.

I suppose this is due to a bug in the program, have you observed this already?
I thank you in advance for your time, and I hope this will be useful. Please tell me if you need any other detail.

Simone

**Comment by rchikhi** [comment]
Hi Simone,

1) It makes sense that BCALM outputs way more unitigs than reference contigs.

2) Regarding the small difference in kmer counts this is odd. Could you please run a third kmer counter, e.g. KMC3 https://github.com/refresh-bio/KMC to see if it agrees with one method or the other?

Rayan

**Comment by simonepignotti** [comment]
Hi Rayan,

1. Yes absolutely, but I found weird that most unitigs are of length ~k, and that for k=25 I got almost 3 times the size of the reference. Still, this is of course possible.
2. I will run it and post the results.

Thank you for your quick answer!
Simone

**Comment by rchikhi** [comment]
Hi Simone,

Regarding 2. wow yes, indeed. Thanks for reporting it, I am investing this discrepancy in DSK counts.

**Comment by simonepignotti** [comment]
No problem, let me know if you need more infos to reproduce the error

**Comment by rchikhi** [comment]
Hi Simone,
Apologies for the delay in addressing this bug. It has stumped me for a while. Finally I found the issue: the reference FASTA file that you provided contains IUPAC nucleotides:
 ...caaTGGGCTTTCCATATATGGCCTTAATTATGTTGAGGTAGTTTCCTTCTGTTCCTAGTTTGGTG**R**ATGTTTTTTATCAT.....

 and BCALM doesn't handle them so well.

**Comment by rchikhi** [comment]
thanks again for the detailed bug report!
