### ISSUE TITLE
Using KMC's output as input of bcalm / minia?

### ISSUE THREAD

**Issue by haghshenas** [GATB/bcalm#38]
Hi Rayan, 
I hope everything is going well.

Considering that KMC is faster than dsk, is it possible to use KMC's kmer count results for running bcalm/minia and skip the dsk step?

**Comment by rchikhi** [comment]
Dear Ehsan,
KMC is indeed faster but we don't have plans to give up on improving DSK just yet :)
Unfortunately we don't have support for parsing KMC's format yet.
Rayan

**Comment by haghshenas** [comment]
Thanks Rayan, for your response.
Glad to hear that you are still trying to improve DKS 👍 
I'm developing a pipeline in which I use Minia as the first step. I should clarify that Minia/bcalm work perfectly fine even for large genomes. Thank you for this nice piece of software. However, I noticed that a big portion of Minia's run time is taken by DSK. Just thought it might be good to get some speed up there.
Is it going to be difficult to parse and use KMC's format? That would be a nice feature to have.

**Comment by rchikhi** [comment]
Great to hear. Stay tuned for speed-up's in Minia
