### ISSUE TITLE
Issues with installing at 'make -j 8' stage

### ISSUE THREAD

**Issue by Laura-Alex** [GATB/bcalm#40]
Hello,

I have issues with installing bcalm. I managed to get it to work (with some warnings) for the most part, but at the 'make -j 8' step it only loads up to 98% before throwing an error:
c++: internal compiler error: Killed (program cc1plus)

I have no idea how to deal with c++. Help would be much appreciated!

**Comment by rchikhi** [comment]
Hi, perhaps you machine doesn't have much RAM. Please try with just `make` instead of `make -j8`!
