### ISSUE TITLE
Using bcalm2 on a set of k-mers where k is a multiple of 4

### ISSUE THREAD

**Issue by amatur** [GATB/bcalm#46]
Hi, I have a set of k-mers (with k=20) from which I want the compacted unitigs. I was going to make a fasta file out of them, with one k-mer per sequence, as I am okay with the abundance information being lost. But the problem is that, bcalm2 does not work with k-mer size of multiples of 4. Do you know any workaround in this case? 

I saw in the discussion in issue #30 that bcalm2 can take as input a custom HDF5 file that contains counted k-mers. Can I use the hdf5 file generated by DSK as an input to bcalm2? I get error when I try that.

**Comment by rchikhi** [comment]
Hi Amatur, I'd have to investigate that again. For now, could you use k=19 perhaps..?

**Comment by amatur** [comment]
@rchikhi for the few datasets that I had, I used bcalm2 with k=20 anyway (allowing multiples of 4 by modifying bcalm_1.cpp), and thankfully I did not run into any bugs.
