### ISSUE TITLE
BCALM does not compile without ZLIB support

### ISSUE THREAD

**Issue by jfostier** [GATB/bcalm#50]
When ZLIB is not installed on your system, CMake promises it will compile without ZLIB support:

-- Could NOT find ZLIB (missing: ZLIB_DIR)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- zlib not found, compiling without zlib support

yet...

[ 70%] Building CXX object ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/gatb/bank/impl/Bank.cpp.o
In file included from bcalm/gatb-core/gatb-core/src/gatb/bank/impl/Bank.cpp:22:0:
bcalm/gatb-core/gatb-core/src/gatb/bank/impl/BankFasta.hpp:30:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>

Probably some missing #ifndef?

Thanks,

Jan.

**Comment by rchikhi** [comment]
Hi Jan, thanks for letting us know. That cmake message (in HDF5 actually) was misleading, you definitely need zlib for BCALM. I've fixed that.
