### ISSUE TITLE
Compiling bcalm causes trouble when no .git repository is found

### ISSUE THREAD

**Issue by vincent-lacroix** [GATB/bcalm#56]
We included bcalm in KisSplice 2.5.0 (huge speedup in graph construction !)
But when compiling, an error occurs if we do not distribute also the .git repository. The bug occurs specifically when git --version 2.17 (not 2.19) is used.  
This is is due to the following piece of code in CMakeLists.txt 

#############################
#getting git version
#from http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake
exec_program(
    "git"
    ${CMAKE_CURRENT_SOURCE_DIR}
    ARGS "rev-parse --short HEAD"
    OUTPUT_VARIABLE VERSION_SHA1 )

add_definitions( -DGIT_SHA1="${VERSION_SHA1}" )

Replacing it with the following piece of code solves the problem. 

#############################
#getting git version
#from http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake
exec_program(
    "git"
    ${CMAKE_CURRENT_SOURCE_DIR}
    ARGS "rev-parse --short HEAD"
    OUTPUT_VARIABLE VERSION_SHA1 
    RETURN_VALUE ERROR_GIT)

if(!${ERROR_GIT})
    add_definitions( -DGIT_SHA1="${VERSION_SHA1}" )
endif(!${ERROR_GIT})

**Comment by rchikhi** [comment]
thanks for the patch Vincent! will be included in next release, and is currently on master branch.
There was a minor mistake in the if() statement, I've fixed it.
