### ISSUE TITLE
Output of bcalm2 similar to minia 3.2.1 unitigs?

### ISSUE THREAD

**Issue by jelber2** [GATB/bcalm#57]
Hi,

It appears as though the unitig output from `bcalm2` is very similar to the unitig output from `minia` 3.2.1. If one uses the same k-mer values and abundances, are the results about the same?

**Comment by rchikhi** [comment]
Hi yes, the intermediate unitig step of minia is indeed exactly the output of bcalm2.

**Comment by jelber2** [comment]
Okay thanks!
