### ISSUE TITLE
High frequency of nodes with degree of two with length = 2k-1 

### ISSUE THREAD

**Issue by samhorsfield96** [GATB/bcalm#59]
Hi,

I generated some .gfa files using BCALM2 using ~30 Listeria monocytogenes assemblies, and noted a high frequency of nodes with a degree of two (nodes with two uniquely connecting edges) with length equal to 2k-1 base pairs. I found this was the case when using 3 different values of k (21, 25, 31, see attached images). Do you know of any reason why this might occur during unitig generation? 

As an aside, I have also seen the same thing when using different bacterial species, and using a different compressed DBG graph tool (Bifrost).

Many thanks for your help,

Sam

![Node_degree_2_length_k21_hist_BCALM2](https://user-images.githubusercontent.com/57448593/83883303-38701500-a73b-11ea-87a6-5591f3e4d14a.png)
![Node_degree_2_length_k25_hist_BCALM2](https://user-images.githubusercontent.com/57448593/83883313-3ad26f00-a73b-11ea-9e60-da67830ea0c0.png)
![Node_degree_2_length_k31_hist_BCALM2](https://user-images.githubusercontent.com/57448593/83883320-3d34c900-a73b-11ea-9a1b-9ee9148ae4dc.png)

**Comment by rchikhi** [comment]
Hi, I believe you are seeing SNPs / seq errors. A single nucleotide variation would manifest itself as a pattern in the graph with two 2k-1 nodes, see e.g. Fig 2 here: https://hal.inria.fr/hal-01083715/document

**Comment by samhorsfield96** [comment]
Hi @rchikhi 

I see, that's good to know. Thank you very much for your help.

Sam
