### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tseemann** [GATB/bcalm#6]
For packaging.

**Comment by sjackman** [comment]
:+1: Please tag a stable release.

**Comment by sjackman** [comment]
New publication: http://bioinformatics.oxfordjournals.org/content/32/12/i201.short
doi "10.1093/bioinformatics/btw279"

**Comment by rchikhi** [comment]
:ok_hand:

**Comment by sjackman** [comment]
I've added bcalm 2.0.0 to Homebrew-Science: https://github.com/Homebrew/homebrew-science/pull/3797
The precompiled binary bottle is not relocatable, meaning that it can only be installed in the directory in which it was built (`/usr/local` for Mac and `/home/linuxbrew/.linuxbrew` for Linux) which limits its utility. Homebrew checks for the string `/usr/local/Cellar` in the resulting executable, and if it finds it, it marks the bottle as non-relocatable. In the case of `bcalm` it's finding these strings:
```
/Users/sjackman/.homebrew/Library/ENV/4.3/clang  (7.3.0.7030031)
C Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang
C++ Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang++
Installation point: /usr/local/Cellar/bcalm/2.0.0
```
If these strings could be removed from the source code / executable, the bottle could be relocatable.

If you're interested in making this improvement, then on Mac or Linux (with Linuxbrew), run the commands:
```
brew install --build-bottle bcalm
brew bottle -v bcalm
```
to test whether the bottle is relocatable. See below for the current output:

```
❯❯❯ brew install --build-bottle bcalm
❯❯❯ brew bottle -v bcalm
==> Determining homebrew/science/bcalm bottle revision...
==> Bottling bcalm-2.0.0.el_capitan.bottle.1.tar.gz...
tar cf /home/sjackman/work/linuxbrew/bcalm/bcalm-2.0.0.el_capitan.bottle.1.tar bcalm/2.0.0
gzip -f bcalm-bottle.tar
==> Detecting if bcalm-2.0.0.el_capitan.bottle.1.tar.gz is relocatable...
Warning: String '/Users/sjackman/.homebrew' still exists in these files:
/usr/local/Cellar/bcalm/2.0.0/bin/bcalm
 --> match '/Users/sjackman/.homebrew/Library/ENV/4.3/clang  (7.3.0.7030031)' at offset 0x446577
 --> match 'C Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang' at offset 0x4ff4e8
 --> match 'C++ Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang++' at offset 0x4ff8dc
/usr/local/Cellar/bcalm/2.0.0/bin/bglue
 --> match '/Users/sjackman/.homebrew/Library/ENV/4.3/clang  (7.3.0.7030031)' at offset 0x1fbc6d
 --> match 'C Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang' at offset 0x2474e8
 --> match 'C++ Compiler: /Users/sjackman/.homebrew/Library/ENV/4.3/clang++' at offset 0x2478dc
Warning: String '/usr/local/Cellar' still exists in these files:
/usr/local/Cellar/bcalm/2.0.0/bin/bcalm
 --> match 'Installation point: /usr/local/Cellar/bcalm/2.0.0' at offset 0x4ff459
/usr/local/Cellar/bcalm/2.0.0/bin/bglue
 --> match 'Installation point: /usr/local/Cellar/bcalm/2.0.0' at offset 0x247459

./bcalm-2.0.0.el_capitan.bottle.1.tar.gz
  bottle do
    prefix "/Users/sjackman/.homebrew"
    revision 1
    sha256 "c47af4783d58f1aab28c3466a8451bb07f3c72a08ba4fb4c357d1f4c73f3d66a" => :el_capitan
  end
```

**Comment by rchikhi** [comment]
Thanks for putting bcalm into homebrew-science!
I'll look into making the binary relocatable. It has to do with our CMake build system and possibly CMAKE_INSTALL_PREFIX, but I'm not totally clear on what to change yet.
