### ISSUE TITLE
.fa files contain lowercase `km` instead of the documented uppercase `KM`

### ISSUE THREAD

**Issue by sebschmi** [GATB/bcalm#60]
Example: `>0 LN:i:32 KC:i:4 km:f:2.0`
Should be: `>0 LN:i:32 KC:i:4 KM:f:2.0`

**Comment by rchikhi** [comment]
KM is a nonstandard field in GFA, so I left it lowercase. Thanks for reporting though!

**Comment by rchikhi** [comment]
Ahhhh but it was "KM" in BCALM readme! that was a typo, thanks.

**Comment by sebschmi** [comment]
Thank you very much 🙂
________________________________
