### ISSUE TITLE
bcalm 2.2.1 on conda for Mac OS X produces incorrect cDBG (the zombie bug returns!!)

### ISSUE THREAD

**Issue by ctb** [GATB/bcalm#62]
hi folks, the bug we reported for Linux in #37 and #44 is baaaaaack! but this time for Mac OS X!

briefly, bcalm is producing a cDBG where there are links that are not bidirectional.

full details to reproduce are here, https://github.com/spacegraphcats/spacegraphcats/pull/281, summary:

```
git clone https://github.com/spacegraphcats/spacegraphcats/ -b mac_bcalm_problem
conda env create -f spacegraphcats/environment.yml -n sgc-broke2
conda activate sgc-broke2
cd spacegraphcats
make twofoo-test
```

and you can generate it w/o the make & snakemake infrastructure using the following commands (once the downloads etc above are done) --

```
bcalm -in twofoo/bcalm.twofoo.k31.inputlist.txt -out twofoo/bcalm.twofoo.k31 -kmer-size 31 -abundance-min 1
python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 twofoo/bcalm.twofoo.k31.unitigs.fa twofoo_k31_r1/cdbg.gxt twofoo_k31_r1/contigs.fa.gz
```

**Comment by ctb** [comment]
(note, this all works fine on Linux.)

I'm running Mac OS X Catalina, 10.15.6. Note that when this was initially reported I don't think I could reproduce the bug on the previous version of Mac OS X, 10.14, which was what I was running - but since then I've upgraded, and now I can reproduce it (joy!) So it may be Catalina-specific.

please let me know if I can help in any way!

**Comment by rchikhi** [comment]
damn, this bug again heh?  first off, thanks for reporting it. second, yes I'd appreciate your help please for a simple test as I don't have any macos'es conveniently close by. Does the latest version of bcalm, macosx binary, also trigger this bug? https://github.com/GATB/bcalm/releases/download/v2.2.3/bcalm-binaries-v2.2.3-Mac.tar.gz

**Comment by ctb** [comment]
that bcalm binary does work for me!

**Comment by rchikhi** [comment]
great!! thanks for testing it.

**Comment by rchikhi** [comment]
@natir can I please ask for your help once again with updating the bcalm bioconda package you created (and [updated](https://github.com/bioconda/bioconda-recipes/pull/12811) last year)? This time it is because the MacOS version seems to be problematic. We have a new version (v2.2.3) and a linux and Mac binaries here:

Linux: https://github.com/GATB/bcalm/releases/download/v2.2.3/bcalm-binaries-v2.2.3-Linux.tar.gz

OSX: https://github.com/GATB/bcalm/releases/download/v2.2.3/bcalm-binaries-v2.2.3-Mac.tar.gz

thanks in advance!

**Comment by natir** [comment]
Hi,

Bioconda build package from source, I can't use your binary.
Actually bioconda linux version of bcalm is 2.2.3, but build on macOS failed I can try to solve this build issue.

**Comment by rchikhi** [comment]
oh yes, I had forgotten this. Hmm macOs build fails on this new 2.2.3 version but not before on 2.2.1? Feel free to put an issue and I can have a look too

**Comment by natir** [comment]
Pull request bioconda/bioconda-recipes/pull/23309 pass all test and will probably merge near in future.

**Comment by ctb** [comment]
you are wonderful!

**Comment by natir** [comment]
bcalm 2.2.3 is avaible for macOS is bioconda

**Comment by rchikhi** [comment]
great!! thanks very much Pierre

**Comment by ctb** [comment]
I just verified that it is all fixed -- thank you!!
