### ISSUE TITLE
insert unitig disregarding the reverse complement

### ISSUE THREAD

**Issue by LucasBarbosaRocha** [GATB/bcalm#69]
Hello,

Why when inserting: 

> TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

the graph stored its reverse complement:

>0 LN:i:21 KC:i:11 km:f:11.0   L:-:0:-  L:+:0:+ 
AAAAAAAAAAAAAAAAAAAAA

???

Is it possible to insert TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT and the graph insert disregarding the reverse complement and does Bcalm store it the way I requested it? ?

Thank you for your help.
Lucas B. Rocha

**Comment by rchikhi** [comment]
Hi, sorry no, Bcalm can only store canonical kmers.
