### ISSUE TITLE
Option `-out-dir` is not used ?

### ISSUE THREAD

**Issue by Louis-MG** [GATB/bcalm#70]
Each run of bcalm I do, I find the *.unitigs.fa in the directory from which I used bcalm, while the .h5 files are in the right place (chosen with `-out-dir`). I tried finding how to fix it in the .cpp but the option is not present in the commented code of bcalm1 and I couldnt find it in gatb core.

**Comment by rchikhi** [comment]
hi, yes, `-out-dir` behavior isn't great. The way to specify where the unitigs.fa file is created is through `-out`. It's due for a fix some time lateR. (note to myself: https://github.com/GATB/gatb-core/blob/db4e7da969eec8d432a61d1b09d7ab8ac149f468/gatb-core/src/gatb/debruijn/impl/GraphUnitigs.cpp#L870)
