### ISSUE TITLE
bug report on a metagenomics dataset

### ISSUE THREAD

**Issue by PandorasRed** [GATB/bcalm#71]
hello,

i have tried to run bcalm on a metagenomic dataset
the command i used is : 
bcalm -in list-meta -kmer-size 31 -abundance-min 1 -out threshold1list-meta
and the error i got is this : cannot create a union-find data structure, too many elements. This should in fact not even happen. Please contact a BCALM developer

i also run it with -abundance-min 2 and it worked in this case

**Comment by rchikhi** [comment]
hi, can you please paste the full log for abundance-min 1? I indeed don't recommend running with this parameter on large datasets as you likely had tens or hundreds of billions of (mostly erroneous) distinct kmers.

**Comment by PandorasRed** [comment]
here the log:
BCALM 2, version v2.2.3, git commit 40469f3
setting storage type to hdf5
[Approximating frequencies of minimizers ]  100  %   elapsed:   1 min 14 sec   remaining:   0 min 0  sec   cpu:  78.3 %   mem: [  34,   34,   34] MB 
[DSK: nb solid kmers: 43072897543        ]  101  %   elapsed: 197 min 7  sec   remaining:   0 min 0  sec   cpu: 344.5 %   mem: [19037, 19619, 19619] MB 
bcalm_algo params, prefix:threshold1list-meta.unitigs.fa k:31 a:1 minsize:10 threads:96 mintype:1
DSK used 1 passes and 12768 partitions
prior to queues allocation                      18:20:56     memory [current, maxRSS]: [18907, 19619] MB 
[Iterating DSK partitions                ]  0    %   elapsed:   0 min 0  sec   remaining:   0 min 0  secStarting BCALM2                                 18:20:56     memory [current, maxRSS]: [18907, 19619] MB 
[Iterating DSK partitions                ]  99.5 %   elapsed: 483 min 31 sec   remaining:   2 min 35 sec
Number of sequences in glue: 9530402195
Number of pre-tips removed : 0
Buckets compaction and gluing           : 29015.3 secs
Within that, 
                                 creating buckets from superbuckets: 8405.8 secs
                      bucket compaction (wall-clock during threads): 20572.3 secs

                within all bucket compaction threads,
                       adding nodes to subgraphs: 76298.9 secs
         subgraphs constructions and compactions: 90899.1 secs
                  compacted nodes redistribution: 68447.7 secs
Sum of CPU times for bucket compactions: 244051.5 secs
BCALM total wallclock (excl kmer counting): 29016.2 secs
Maximum number of kmers in a subgraph: 978466
Performance of compaction step:

                 Wallclock time spent in parallel section : 20572.3 secs
             Best theoretical speedup in parallel section : 12.4x
Best theor. speedup in parallel section using 1 threads : 1.0x
             Sum of longest bucket compaction for each sb : 19350.6 secs
                       Sum of best scheduling for each sb : 235646.5 secs
Done with all compactions                       02:24:33     memory [current, maxRSS]: [25486, 25654] MB 
bglue_algo params, prefix:threshold1list-meta.unitigs.fa k:31 threads:96
Starting bglue with 96 threads                  02:24:33     memory [current, maxRSS]: [25486, 25654] MB 
number of sequences to be glued: 9530402195        02:24:56     memory [current, maxRSS]: [25486, 25654] MB 
4892269572 marked kmers, 4384383612 unmarked kmers        03:11:09     memory [current, maxRSS]: [62814, 62825] MB 
created vector of hashes, size approx 37325 MB)        03:11:09     memory [current, maxRSS]: [62814, 62825] MB 
pass 1/3, 2446134786 unique hashes written to disk, size 18662 MB        03:19:52     memory [current, maxRSS]: [25488, 62831] MB 
4892052562 marked kmers, 4384383612 unmarked kmers        04:07:35     memory [current, maxRSS]: [62811, 62831] MB 
created vector of hashes, size approx 37323 MB)        04:07:35     memory [current, maxRSS]: [62811, 62831] MB 
pass 2/3, 2446026281 unique hashes written to disk, size 18661 MB        04:16:18     memory [current, maxRSS]: [25488, 62831] MB 
4892098644 marked kmers, 4384383612 unmarked kmers        05:05:14     memory [current, maxRSS]: [62812, 62831] MB 
created vector of hashes, size approx 37323 MB)        05:05:14     memory [current, maxRSS]: [62812, 62831] MB 
pass 3/3, 2446049322 unique hashes written to disk, size 18661 MB        05:13:58     memory [current, maxRSS]: [25488, 62831] MB 
loaded all unique UF elements (7338210389) into a single vector of size 55986 MB        05:15:26     memory [current, maxRSS]: [81474, 81474] MB 
[Building BooPHF]  100  %   elapsed:  11 min 1  sec   remaining:   0 min 0  sec
Bitarray     34564383616  bits (100.00 %)   (array + ranks )
final hash             0  bits (0.00 %) (nb in final hash 0)
UF MPHF constructed (4120 MB)                   05:26:31     memory [current, maxRSS]: [25816, 81812] MB 
cannot create a union-find data structure, too many elements. This should in fact not even happen. Please contact a BCALM developer

**Comment by rchikhi** [comment]
Thanks. 43 billion distinct k-mers, that's indeed bigger than anything ever tested. I guess this is the limit of BCALM2 for now. There's no plan to lift it for now, but I'll keep that use-case in mind.
