### ISSUE TITLE
Add header description with `-all-abundance-counts`

### ISSUE THREAD

**Issue by enricorox** [GATB/bcalm#72]
Hi!
I have a file generated with `-all-abundance-counts`
It's not clear what `ab:Z:2 2` means in 

> \>0 LN:i:16 ab:Z:2 2   L:-:27692788:+  L:+:28492175:+ L:+:32855043:+ 
> AATTGCGGTTTTTTGC

Can you add the description to the README.md?

**Comment by enricorox** [comment]
Ok, I figured it out by myself. 

In the unitig I have two kmer (with k=15):
*  `AATTGCGGTTTTTTG` has abundance 2
*  `ATTGCGGTTTTTTGC` has abundance 2

I've made a pull request (a2646e9f01ce64ee3cc8a5847ecb3c2177d238dd) with the changes in the readme.

**Comment by rchikhi** [comment]
thanks much!
