### ISSUE TITLE
Is the output file reproducible?

### ISSUE THREAD

**Issue by enricorox** [GATB/bcalm#74]
I launched bcalm (40469f3) two times on the my department's cluster with the same parameters except of `-nb-cores` (4 vs 8) but I obtained different files.

Then I launched again the same versione of bcalm on my PC with `-nb-cores 4` and I have a different file again!

The command: `bcalm -max-memory 16000 -nb-cores 8 -kmer-size 31 -abundance-min 1 -in "SRR001665_1.fasta" -all-abundance-counts`

So my question: Is the output file reproducible? Or there are race conditions/randomizations that makes the file different every time?

**Comment by rchikhi** [comment]
As far as I remember, a safe way to make the output reproducible is to add `-nb-cores 1 -nb-glue-partitions 200`.

**Comment by rchikhi** [comment]
Though, for bcalm, the output should be identical up to reordering of the output sequences..
