### ISSUE TITLE
Counting kmers error

### ISSUE THREAD

**Issue by Mathiascode3** [GATB/bcalm#77]
Hello, I have a problem with step 2 "counting kmer" DSK of bcalm.
When I get to this step, I always get the same error that stops the process.
I run snakemake --cores 4, and my machine parameters are :
--cpus-per-task=4
 --mem=16G

![Capture d’écran du 2024-03-25 15-47-45](https://github.com/GATB/bcalm/assets/147552192/e2698503-7a4a-4b34-87ac-9e6ab11981bc)

Thanks for your help if you have any idea of the problem ?

**Comment by rchikhi** [comment]
Try putting the `/usr/bin/time` command before bcalm to see memory usage

**Comment by Mathiascode3** [comment]
It was indeed a ram and cpu problem, I didn't correctly mention what I wanted on the cluster I was using.
Thank you very much, please forgive me for the inconvenience, have a good day.
